docs: add more content and translations
okp4/team-wiki pull request #41
Opened 2023-05-03 12:47 UTC by AnjaMis

This PR adds more content regarding agility, kanban and rituals. Basically it adds content about our DOR, newly introduced rituals (backlog refinement, planning poker) and their translations.

🚨 Please check the french translation, I have no idea if what I added here makes sense or not. 

To be able to check translations in the localhost, run `yarn build` and then `yarn run serve`

2023-05-03 20:06 UTC, MdechampG requested changes

2023-05-03 20:06 UTC, MdechampG commented on i18n/fr/docusaurus-plugin-content-docs/current/process/kanban.md
> +- attaché à une epic
```suggestion
- rattachement à une epic
```

2023-05-03 20:06 UTC, MdechampG commented on i18n/fr/docusaurus-plugin-content-docs/current/process/kanban.md
> +- estimation (réunion de planification)
```suggestion
- estimation (réunion de planning poker)
```

2023-05-03 20:06 UTC, MdechampG commented on i18n/fr/docusaurus-plugin-content-docs/current/process/rituals.md
> +📆 **Réunions quotidiennes**
```suggestion
📆 **Réunion quotidienne**
```

2023-05-03 20:06 UTC, MdechampG commented on i18n/fr/docusaurus-plugin-content-docs/current/process/rituals.md
> +📆 **Réunions hebdomadaires**
```suggestion
📆 **Réunion hebdomadaire**
```

2023-05-03 20:06 UTC, MdechampG commented on i18n/fr/docusaurus-plugin-content-docs/current/process/rituals.md
> +📆 **Réunions de projets**
```suggestion
📆 **Réunion de projets**
```

2023-05-03 20:06 UTC, MdechampG commented on i18n/fr/docusaurus-plugin-content-docs/current/process/rituals.md
>  - Équipes de projet et de marketing et communication
```suggestion
- Équipes projets et marketing et communication
```

2023-05-03 20:06 UTC, MdechampG commented on i18n/fr/docusaurus-plugin-content-docs/current/process/rituals.md
> +📆 **Le backlog refinement**
```suggestion
📆 **Le raffinage du backlog**
```

2023-05-03 20:06 UTC, MdechampG commented on i18n/fr/docusaurus-plugin-content-docs/current/process/rituals.md
> +- L'équipe produit présente de nouvelles user story à l'équipe technique.
```suggestion
- L'équipe produit présente de nouvelles user stories à l'équipe technique.
```

2023-05-03 20:06 UTC, MdechampG commented on i18n/fr/docusaurus-plugin-content-docs/current/process/rituals.md
> +- Pour estimer l'effort de travail pour les nouvelles user story
```suggestion
- Pour estimer l'effort de travail pour les nouvelles user stories
```

2023-05-03 20:07 UTC, MdechampG commented
Thank you @AnjaMis only few things to correct :)

2023-05-12 08:34 UTC, ccamel approved these changes
Great 👍

2023-05-12 11:21 UTC, MdechampG approved these changes
LGTM Thanks @AnjaMis !

2023-05-12 11:27 UTC, merged