feat: add dev wiki
okp4/team-wiki pull request #43
Opened 2023-05-19 19:12 UTC by AnjaMis

This PR adds a dev-wiki tab in the navbar with its content and translations. 

To test the content in french run `yarn build` and then `yarn run serve`.

🚨 Please please double check the translation part.

2023-05-20 10:08 UTC, amimart requested changes
I don't understand the purpose of providing french translations on technical processes as the working langage on OKP4 repositories is English.

Moreover, once translated, some technical concepts may be differently understood, I really think it is important to pick a single technical langage to be able to communicate.

I may not see the idea behind, but I'd rather keep only the english version, it'll by the way ease future maintenance on this documentation.

2023-05-22 08:29 UTC, AnjaMis commented
@amimart I see your point, if @MdechampG agrees, I can remove the translations and keep everything in English even when the user switches the website to FR. :)

2023-05-23 05:38 UTC, amimart approved these changes

2023-05-23 09:03 UTC, MdechampG approved these changes
LGTM :)

2023-05-23 09:50 UTC, ccamel approved these changes

2023-05-23 09:51 UTC, merged